### ISSUE TITLE
I'm also making this right now, hopefully we can help out if either gets stuck 👍 

### ISSUE THREAD

**Issue by bmcilw1** [RoXioTD/sveltekit-tailwindcss-starter#1]
Nice job!

Here's how far I've [got](https://github.com/bmcilw1/technicallyemployed/tree/tailwind)

Links I've tried to follow
- Very recent article https://linu.us/sveltekit-with-tailwindcss-v3  (but I'm not able to open the dev server yet 😞  "This page isn’t working/ localhost is currently unable to handle this request.")
- Just found this one: https://medium.com/geekculture/how-to-start-with-svelte-and-tailwind-css-5df7e084af03

And I found your repo so I figured I'd loop you in

**Comment by bmcilw1** [comment]
And... got my issue figured out. I needed to rename a `.js` config to `.cjs`. Great!

**Comment by RoXioTD** [comment]
@bmcilw1 Yeah you are correct. The `tailwind.config.js` and `postcss.config.js` should be `.cjs` files. I will fix this now. Thx
